//Course Actions
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

//Dashboard Actions
export const CREATE_TILE = 'CREATE_TILE';
export const INCREMENT_TILE = 'INCREMENT_TILE';
export const DECREMENT_TILE = 'DECREMENT_TILE';