//Ajax actions 
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

//Course Actions
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

//Dashboard Layout Actions
export const CREATE_TILE = 'CREATE_TILE';
export const INCREMENT_TILE = 'INCREMENT_TILE';
export const DECREMENT_TILE = 'DECREMENT_TILE';
export const UPDATE_TILE = 'UPDATE_TILE';

export const LOAD_LAYOUT_SUCCESS = 'LOAD_LAYOUT_SUCCESS';

//Dashboard General Actions
export const LOAD_DASHBOARD_SUCCESS = 'LOAD_DASHBOARD_SUCCESS';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';

//Data actions
export const LOAD_DATA_WIDGET_SUCCESS = "LOAD_DATA_WIDGET_SUCCESS";

//Role actions
export const LOAD_ALL_ROLES_SUCCESS = "LOAD_ALL_ROLES_SUCCESS";