//Ajax actions 
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

//Course Actions
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';


//Dashboard General Actions
export const LOAD_DASHBOARD_SUCCESS = 'LOAD_DASHBOARD_SUCCESS';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const REMOVE_DASHBOARD = 'REMOVE_DASHBOARD';
export const ADD_DASHBOARD = 'ADD_DASHBOARD';
export const SAVE_NEW_LAYOUT = 'SAVE_NEW_LAYOUT';
//Dashboard Default Actions
export const LOAD_DEFAULT_DASHBOARD_SUCCESS = "LOAD_DEFAULT_DASHBOARD_SUCCESS";

//Data actions
export const LOAD_DATA_WIDGET_SUCCESS = "LOAD_DATA_WIDGET_SUCCESS";
export const LOAD_DATA_SUCCESS_API = "LOAD_DATA_SUCCESS_API";
export const LOAD_ALL_DATASOURCES_SUCCESS = "LOAD_ALL_DATASOURCES_SUCCESS";

//Role actions
export const LOAD_ALL_ROLES_SUCCESS = "LOAD_ALL_ROLES_SUCCESS";
export const UPLOAD_NEW_ROLE = "UPLOAD_NEW_ROLE";

//Permission actions
export const LOAD_PERMISSIONS_SUCCESS = "LOAD_PERMISSIONS_SUCCESS";

//Widget actions
export const REMOVE_WIDGET_SUCCESS = "REMOVE_WIDGET_SUCCESS";
export const ADD_WIDGET_SUCCESS = "ADD_WIDGET_SUCCESS";

//Manage defautl dashboard actions
export const TEST_AND_WAIT = "TEST_AND_WAIT";

//Manage widget actions
export const TEST_AND_TEMP = "TEST_AND_TEMP";